apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sykmeldingalerts
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  groups:
    - name: teamsykmelding prod-gcp alarmer
      rules:
        - alert: teamsykmelding-app-nede
          expr: kube_deployment_status_replicas_available{namespace="teamsykmelding"} == 0
          for: 2m
          annotations:
            consequence: Application is unavailable
            action: "Se `kubectl kubectl get pod  | grep {{ $labels.deployment }}` for å se podder, og `kubectl logs $podnavn` for logger"
            summary: "{{ $labels.deployment }} er nede"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: teamsykmelding-kontinuerlig-restart
          expr: sum(increase(kube_pod_container_status_restarts_total{namespace="teamsykmelding"}[30m])) by (container) > 3
          for: 2m
          annotations:
            consequence: Application is unavailable
            action: "Se `kubectl describe pod {{ $labels.container }}` for events, og `kubectl logs {{ $labels.container }}` for logger"
            summary: "{{ $labels.container }} har restartet flere ganger siste halvtimen!"
          labels:
            namespace: teamsykmelding
            severity: warning
        - alert: teamsykmelding-error-logging
          expr: sum(rate(logd_messages_total{log_team="teamsykmelding", log_level=~"Fatal|Error", log_app!~'wonderwall|linkerd-init|cloudsql-proxy|vks-init|.*redis'}[5m])) by(log_app) > 0
          for: 2m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk hvorfor {{ $labels.log_app }} har logget Error i løpet av de siste 5 minuttene"
            summary: "{{ $labels.log_app }} rapporterer error i loggene"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: teamsykmeldig-app-cpu
          expr: (sum(kube_pod_container_resource_requests{namespace="teamsykmelding",resource="cpu", container!="linkerd-proxy",container!="cloudsql-proxy",container!="secure-logs-configmap-reload",container!="secure-logs-fluentd"}) by (container) - sum(rate(container_cpu_usage_seconds_total{namespace="teamsykmelding",container!="linkerd-proxy",container!="cloudsql-proxy",container!="secure-logs-configmap-reload",container!="secure-logs-fluentd",container!="POD", container!=""}[5m])) by (container)) < 0
          for: 5m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk CPU for {{ $labels.container }}, kanskje juster opp requested eller justere opp antall pods"
            summary: "{{ $labels.container }} bruker mer CPU enn angitt"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: teamsykmeldig-app-ram
          expr: sum(kube_pod_container_resource_requests{namespace="teamsykmelding", resource="memory", container!="linkerd-proxy",container!="cloudsql-proxy",container!="secure-logs-configmap-reload",container!="secure-logs-fluentd"}) by (container) - sum(container_memory_working_set_bytes{namespace="teamsykmelding",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="secure-logs-configmap-reload",container!="secure-logs-fluentd",container!="POD", container!=""}) by (container) < 0
          for: 5m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk RAM for {{ $labels.container }}, kanskje juster opp requested eller justere opp antall pods"
            summary: "{{ $labels.container }} bruker mer RAM enn angitt"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: syfosmmottak-ugyldige-sykmeldinger
          expr: sum(increase(syfosmmottak_invalid_message_no_notice_count_total[10m])) > 50
          for: 10m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk logger, og om det kan ha blitt innført feil"
            summary: "syfosmmottak har mottatt unormalt mange ugyldige sykmeldinger"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: syfosmregler-avviste-sykmeldinger
          expr: sum(increase(syfosmregler_rule_hit_status_counter_total{app=~"syfosmregler",rule_status="INVALID"}[30m])) by (rule_status) > 120
          for: 10m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk logger, og om det kan ha blitt innført feil"
            summary: "syfosmregler har avvist unormalt mange sykmeldinger"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: syfosminfotrygd-mange-manuelle-oppg
          expr: (100 * sum(rate(syfosminfotrygd_rule_hit_status_counter_total{rule_status="MANUAL_PROCESSING"}[10m])) / sum(rate(syfosminfotrygd_rule_hit_status_counter[10m]))) > 90
          for: 10m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk logger, kanskje Infotrygd har problemer"
            summary: "syfosminfotrygd oppretter unormalt mange oppgaver"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: pale-2-ugyldige-legeerklaeringer
          expr: sum(increase(pale2_invalid_message_no_notice_count_total[10m])) > 20
          for: 10m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk logger, og om det kan ha blitt innført feil"
            summary: "pale-2 har mottatt unormalt mange ugyldige legeerklæringer"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: teamsykmelding-kafka-offset
          expr: kafka_consumergroup_group_topic_sum_lag{topic=~"teamsykmelding.*", group!~"dvh-sykm|isdialogmelding|isnarmesteleder-v2|min-side-.*|.*soknad.*|syfosyketilfelle-.*|notifikasjon-.*"} > 500
          for: 10m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk om {{ $labels.group }} leser fra kafka"
            summary: "{{ $labels.group }} kafka-lag for topic {{ $labels.topic }} er høyt"
          labels:
            namespace: teamsykmelding
            severity: danger