apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sykmeldingalerts
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  groups:
    - name: teamsykmelding prod-gcp alarmer
      rules:
        - alert: teamsykmelding-app-nede
          expr: kube_deployment_status_replicas_available{namespace="teamsykmelding"} == 0
          for: 2m
          annotations:
            consequence: Application is unavailable
            action: "Se `kubectl get pod | grep {{ $labels.deployment }}` for å se podder, og `kubectl logs $podnavn` for logger"
            summary: "{{ $labels.deployment }} er nede"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: teamsykmelding-kontinuerlig-restart
          expr: sum(increase(kube_pod_container_status_restarts_total{namespace="teamsykmelding", container!="secure-logs-fluentd", container!="cloudsql-proxy", container!="linkerd-proxy", container!="elector", container!="secure-logs-configmap-reload"}[30m])) by (container) > 3
          for: 2m
          annotations:
            consequence: Application is unavailable
            action: "Se `kubectl describe pod {{ $labels.container }}` for events, og `kubectl logs {{ $labels.container }}` for logger"
            summary: "{{ $labels.container }} har restartet flere ganger siste halvtimen!"
          labels:
            namespace: teamsykmelding
            severity: warning
        - alert: teamsykmelding-error-logging
          expr: sum(rate(logd_messages_total{log_team="teamsykmelding", log_level=~"Fatal|Error", log_app!~'wonderwall|linkerd-init|cloudsql-proxy|vks-init|.*redis'}[5m])) by(log_app) > 0
          for: 5m
          annotations:
            consequence: Application is logging error
            action: "Sjekk hvorfor {{ $labels.log_app }} har logget Error i løpet av de siste 5 minuttene https://logs.adeo.no/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-5m,to:now))&_a=(columns:!(level,message,envclass,application,pod),filters:!(),interval:auto,query:(language:lucene,query:'%20%2Bapplication:%22{{ $labels.log_app }}%22%20%2Benvclass:%22p%22%20%2Blevel:Error'),sort:!(!('@timestamp',desc)))"
            summary: "{{ $labels.log_app }} rapporterer error i loggene"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: teamsykmeldig-app-cpu
          expr: (sum(kube_pod_container_resource_requests{namespace="teamsykmelding",resource="cpu", container!="linkerd-proxy",container!="cloudsql-proxy",container!="secure-logs-configmap-reload",container!="secure-logs-fluentd"}) by (pod) - sum(rate(container_cpu_usage_seconds_total{namespace="teamsykmelding",container!="linkerd-proxy",container!="cloudsql-proxy",container!="secure-logs-configmap-reload",container!="secure-logs-fluentd",container!="POD", container!=""}[5m])) by (pod)) < 0
          for: 5m
          annotations:
            consequence: Application may use up CPU
            action: "Sjekk CPU for {{ $labels.pod }}, kanskje juster opp requested eller justere opp antall pods"
            summary: "{{ $labels.app }} : {{ $labels.pod }} bruker mer CPU enn angitt"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: teamsykmeldig-app-ram
          expr: sum(kube_pod_container_resource_requests{namespace="teamsykmelding", resource="memory", container!="linkerd-proxy",container!="cloudsql-proxy",container!="secure-logs-configmap-reload",container!="secure-logs-fluentd"}) by (pod) - sum(container_memory_working_set_bytes{namespace="teamsykmelding",container!="linkerd-init",container!="linkerd-proxy",container!="cloudsql-proxy",container!="secure-logs-configmap-reload",container!="secure-logs-fluentd",container!="POD", container!=""}) by (pod) < 0
          for: 5m
          annotations:
            consequence: Application may use up RAM
            action: "Sjekk RAM for {{ $labels.pod }}, kanskje juster opp requested eller justere opp antall pods"
            summary: "{{ $labels.app }} : {{ $labels.pod }} bruker mer RAM enn angitt"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: syfosmmottak-ugyldige-sykmeldinger
          expr: sum(increase(syfosmmottak_invalid_message_no_notice_count_total[10m])) > 50
          for: 10m
          annotations:
            consequence: Application is produces a lot og invalid messages
            action: "Sjekk logger, og om det kan ha blitt innført feil"
            summary: "syfosmmottak har mottatt unormalt mange ugyldige sykmeldinger"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: syfosmregler-avviste-sykmeldinger
          expr: sum(increase(syfosmregler_rule_hit_status_counter_total{app=~"syfosmregler",rule_status="INVALID"}[30m])) by (rule_status) > 120
          for: 10m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk logger, og om det kan ha blitt innført feil"
            summary: "syfosmregler har avvist unormalt mange sykmeldinger"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: syfosminfotrygd-mange-manuelle-oppg
          expr: (100 * sum(rate(syfosminfotrygd_rule_hit_status_counter_total{rule_status="MANUAL_PROCESSING"}[10m])) / sum(rate(syfosminfotrygd_rule_hit_status_counter[10m]))) > 90
          for: 10m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk logger, kanskje Infotrygd har problemer"
            summary: "syfosminfotrygd oppretter unormalt mange oppgaver"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: pale-2-ugyldige-legeerklaeringer
          expr: sum(increase(pale2_invalid_message_no_notice_count_total[10m])) > 20
          for: 10m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk logger, og om det kan ha blitt innført feil"
            summary: "pale-2 har mottatt unormalt mange ugyldige legeerklæringer"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: teamsykmelding-kafka-offset
          expr: kafka_consumergroup_group_topic_sum_lag{topic=~"teamsykmelding.*", group!~"dvh-sykm|isdialogmelding|isnarmesteleder-v2|min-side-.*|.*soknad.*|syfosyketilfelle-.*|notifikasjon-.*|syfosoknad-consumer|redigerte-egenmeldingsdager|sykmelding-yrkesskade-consumer|teamsykmelding-pik"} > 500
          for: 10m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk om {{ $labels.group }} leser fra kafka"
            summary: "{{ $labels.group }} kafka-lag for topic {{ $labels.topic }} er høyt"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: syfosmsak-stream-kafka-offset
          expr: up{app="syfosmsak-stream", job="kubernetes-pods"} == 0
          for: 1m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk om syfosmsak-stream leser fra kafka"
            summary: "syfosmsak-stream kafka-lag er høyt"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: dinesykmeldte-kafka-offset
          expr: kafka_consumergroup_group_sum_lag{group=~"dinesykmeldte-backend"} > 100
          for: 1m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk om dinesykmeldte-kafka leser fra kafka"
            summary: "dinesykmeldte-kafka kafka-lag er høyt"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: syfosmoppgave-stream-kafka-offset
          expr: kafka_consumergroup_group_sum_lag{group=~"teamsykmelding.syfosmoppgave-stream_stream_"} > 100
          for: 1m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk om syfosmoppgave-stream leser fra kafka"
            summary: "syfosmoppgave-stream kafka-lag er høyt"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: narmesteleder-arbeidsforhold-kafka-offset
          expr: kafka_consumergroup_group_sum_lag{group=~"narmesteleder-arbeidsforhold"} > 100
          for: 1m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk om narmesteleder-arbeidsforhold leser fra kafka"
            summary: "narmesteleder-arbeidsforhold kafka-lag er høyt"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: syfosmarena-stream-kafka-offset
          expr: kafka_consumergroup_group_sum_lag{group=~"teamsykmelding.syfosmarena-stream_stream_"} > 100
          for: 1m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk om syfosmarena-stream leser fra kafka"
            summary: "syfosmarena-stream kafka-lag er høyt"
          labels:
            namespace: teamsykmelding
            severity: danger
        - alert: sykmeldinger-arbeidsgiver-kafka-offset
          expr: kafka_consumergroup_group_sum_lag{group=~"sykmeldinger-arbeidsgiver-consumer-v2"} > 100
          for: 1m
          annotations:
            consequence: Application is unavailable
            action: "Sjekk om sykmeldinger-arbeidsgiver leser fra kafka"
            summary: "sykmeldinger-arbeidsgiver kafka-lag er høyt"
          labels:
            namespace: teamsykmelding
            severity: danger
